### ISSUE TITLE
Теорема 4.3

### ISSUE THREAD

**Issue by Pr0f1D0c** [dainbow/DifferentialEquationsMIPT#10]
https://github.com/dainbow/DifferentialEquationsMIPT/blob/da3a8ac909f41fe59b5497c59ebf2a2c9cdb18e4/main.tex#L1191

Если существует $x_0 \in I$, что $y_1(x_0),\,\cdots,\,y_k(x_0)$ линейно **зависимы** (сейчас независимы), то найдётся нетривиальная линейная комбинация

**Comment by dainbow** [comment]
Thanks! The commit 13a80d0 solved the issue...
