### ISSUE TITLE
Док-во теоремы 4.4

### ISSUE THREAD

**Issue by Pr0f1D0c** [dainbow/DifferentialEquationsMIPT#11]
https://github.com/dainbow/DifferentialEquationsMIPT/blob/13a80d07e193f05d63698726e95be01109e755ee/main.tex#L1203

Утверждается, что т.к. решения построены из ЛНЗ векторов в одной точке, то сами решения ЛНЗ. Тут, мне кажется, стоит более явно сослаться на лемму 4.2 или доказать от противного:
Допустим, решения получились ЛЗ, несмотря на то, что построены из ЛНЗ векторов. Тогда, в силу отрицания (а не обратного, что можно легко перепутать) леммы 4.2 получаем, что во всех точках вектора ЛЗ, а это противоречие с точкой $x0$.

**Comment by dainbow** [comment]
Thanks! Fixed in [225151c](https://github.com/dainbow/DifferentialEquationsMIPT/commit/225151cd3ba6fe156b1ad512d8264acbe39ce4fd)
