### ISSUE TITLE
доказательство леммы 3.2

### ISSUE THREAD

**Issue by Pr0f1D0c** [dainbow/DifferentialEquationsMIPT#7]
https://github.com/dainbow/DifferentialEquationsMIPT/blame/62ca709af6b86163908aa6837aee2374ec2bf1ae/main.tex#L728

Тут лучше уточнить, что y \equiv 0 -- это решение, так как мы имеем дело с однородным уравнением. Независимо от этого y = \sum y_i -- решение, как линейная комбинация решений. И уже после этого утверждается, что они совпадают в силу единственности РЗК.

**Comment by dainbow** [comment]
Thanks for the issue! Fixed
