### ISSUE TITLE
Единственность Линейные однородные ДУ $n$-го порядка с постоянными коэффициентами

### ISSUE THREAD

**Issue by Pr0f1D0c** [dainbow/DifferentialEquationsMIPT#8]
https://github.com/dainbow/DifferentialEquationsMIPT/blame/62ca709af6b86163908aa6837aee2374ec2bf1ae/main.tex#L774

Фактически, там нет единственности. Единственность есть для РЗК -- нужно сначала сказать про задачу коши.

**Comment by dainbow** [comment]
Thanks for the issue! Fixed
