### ISSUE TITLE
x в показателе. Доказательство теоремы 3.2

### ISSUE THREAD

**Issue by Pr0f1D0c** [dainbow/DifferentialEquationsMIPT#9]
https://github.com/dainbow/DifferentialEquationsMIPT/blob/62ca709af6b86163908aa6837aee2374ec2bf1ae/main.tex#LL947C2-L947C2

Тут в экспоненте должен быть x, вероятно.

**Comment by dainbow** [comment]
Thanks for the issue! Fixed
